export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export type UPDATE_USER_LIST = typeof UPDATE_USER_LIST;

export const UPDATE_SINGLE_USER_DATA = 'UPDATE_SINGLE_USER_DATA';
export type UPDATE_SINGLE_USER_DATA = typeof UPDATE_SINGLE_USER_DATA;

export const UPDATE_SINGLE_USER_FIELDS = 'UPDATE_SINGLE_USER_FIELDS';
export type UPDATE_SINGLE_USER_FIELDS = typeof UPDATE_SINGLE_USER_FIELDS;